---

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: no-commit-to-branch
      - id: fix-byte-order-marker
      - id: check-json
      - id: pretty-format-json
        args: ['--no-sort-keys', '--autofix']
